"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _hero_title from './hero-title.bones.json'
import _about_section from './about-section.bones.json'
import _team_section from './team-section.bones.json'
import _initiatives_section from './initiatives-section.bones.json'

registerBones({
  "hero-title": _hero_title,
  "about-section": _about_section,
  "team-section": _team_section,
  "initiatives-section": _initiatives_section,
})
